# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='selling_area_name',
            new_name='market_name',
        ),
    ]
