# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180309_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
