# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180210_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
