# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180210_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='barcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
