# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sku_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Registration'),
        ),
    ]
