# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180214_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Group'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
