# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180215_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='hash_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skuimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Sku'),
        ),
    ]
